# Generated by Django 6.0.3 on 2026-04-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['-importance']},
        ),
        migrations.AlterField(
            model_name='weightconfig',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
