# Generated by Django 6.0.3 on 2026-04-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_decision_options_alter_option_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('career', 'Career'), ('fun', 'Fun'), ('social', 'Social'), ('finance', 'Finance'), ('growth', 'Growth')], max_length=20),
        ),
    ]
